# Generated by Django 5.1.7 on 2025-03-27 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='email',
            field=models.EmailField(default='email_padrao@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(default='Sobrenome Padrão', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
