# Generated by Django 5.1.7 on 2025-03-29 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfil_data_nascimento_perfil_email_perfil_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='link',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
