# Generated by Django 5.1.7 on 2025-04-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfil_avatar_perfil_biografia_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
