# Generated by Django 5.1.7 on 2025-04-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_perfil_data_nascimento_perfil_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
